# ==============================================================================
# GENERAL & USER INTERFACE
# ==============================================================================
profile=gpu-hq
osc=no
title-bar=no

# ==============================================================================
# VIDEO UP-SCALING & SHADERS (Anime4K - Mode A HQ)
# ==============================================================================
glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"

# ==============================================================================
# RESUME PLAYBACK (WATCH LATER)
# ==============================================================================
save-position-on-quit=yes
watch-later-options-add=start
watch-later-directory="~~/watch-later"

# ==============================================================================
# CACHE & BUFFER MANAGEMENT
# ==============================================================================
cache=yes
demuxer-max-bytes=3000MiB
demuxer-max-back-bytes=500MiB

# Cache Directories
gpu-shader-cache-dir="~~/cache/shaders"
icc-cache-dir="~~/cache/icc"
ytdl-raw-options-append=cache-dir="~~/cache/yt-dlp"